### ISSUE TITLE
compilation error android

### ISSUE THREAD

**Issue by jonathanrcarter** [pegli/ti_touchdb#101]
I compiled the version from github and implemented it.  I can't stop this error appearing and stopping the app build.  can you help?

[INFO]  Running dexer: /Library/Java/JavaVirtualMachines/jdk1.7.0_75.jdk/Contents/Home/bin/java "-Xmx1024M" "-XX:-UseGCOverheadLimit" "-Djava.ext.dirs=/opt/android_sdk/android-sdk-mac_x86/platform-tools" "-jar" "/opt/android_sdk/android-sdk-mac_x86/build-tools/21.1.2/lib/dx.jar" "--dex" "--output=/Users/jc/Documents/Titanium Studio Workspace/mht/build/android/bin/classes.dex" "/Users/jc/Documents/Titanium Studio Workspace/mht/build/android/bin/classes" "/Library/Application Support/Titanium/mobilesdk/osx/3.5.0.GA/android/lib/titanium-verify.jar" "/Library/Application Support/Titanium/modules/android/ti.map/2.2.3/map.jar" "/Library/Application Support/Titanium/modules/android/ti.map/2.2.3/lib/google-play-services.jar" "/Library/Application Support/Titanium/modules/android/facebook/3.0.3/facebook.jar" "/Library/Application Support/Titanium/modules/android/com.obscure.titouchdb/1.2.2/titouchdb.jar" "/Library/Application Support/Titanium/modules/android/com.obscure.titouchdb/1.2.2/lib/cbl_collator_so-1.0.4-28.jar" "/Library/Application Support/Titanium/modules/android/com.obscure.titouchdb/1.2.2/lib/commons-io-2.0.1.jar" "/Library/Application Support/Titanium/modules/android/com.obscure.titouchdb/1.2.2/lib/commons-logging-1.1.3.jar" "/Library/Application Support/Titanium/modules/android/com.obscure.titouchdb/1.2.2/lib/couchbase-lite-android-1.0.4-28.jar" "/Library/Application Support/Titanium/modules/android/com.obscure.titouchdb/1.2.2/lib/couchbase-lite-java-1.0.4-28.jar" "/Library/Application Support/Titanium/modules/android/com.obscure.titouchdb/1.2.2/lib/couchbase-lite-java-core-1.0.4-28.jar" "/Library/Application Support/Titanium/modules/android/com.obscure.titouchdb/1.2.2/lib/couchbase-lite-java-javascript-1.0.4-28.jar" "/Library/Application Support/Titanium/modules/android/com.obscure.titouchdb/1.2.2/lib/couchbase-lite-java-listener-1.0.4-28.jar" "/Library/Application Support/Titanium/modules/android/com.obscure.titouchdb/1.2.2/lib/couchbase-lite-java-native-1.0.4-28.jar" "/Library/Application Support/Titanium/modules/android/com.obscure.titouchdb/1.2.2/lib/httpclient-4.0-beta1.jar" "/Library/Application Support/Titanium/modules/android/com.obscure.titouchdb/1.2.2/lib/httpcore-4.0-beta2.jar" "/Library/Application Support/Titanium/modules/android/com.obscure.titouchdb/1.2.2/lib/jackson-core-asl-1.9.2.jar" "/Library/Application Support/Titanium/modules/android/com.obscure.titouchdb/1.2.2/lib/jackson-mapper-asl-1.9.2.jar" "/Library/Application Support/Titanium/modules/android/com.obscure.titouchdb/1.2.2/lib/rhino-1.7R3.jar" "/Library/Application Support/Titanium/modules/android/com.obscure.titouchdb/1.2.2/lib/servlet-2-3.jar" "/Library/Application Support/Titanium/modules/android/com.obscure.titouchdb/1.2.2/lib/stateless4j-2.4.0.jar" "/Library/Application Support/Titanium/modules/android/com.obscure.titouchdb/1.2.2/lib/webserver-2-3.jar" "/Library/Application Support/Titanium/mobilesdk/osx/3.5.0.GA/android/kroll-v8.jar" "/Library/Application Support/Titanium/mobilesdk/osx/3.5.0.GA/android/modules/titanium-analytics.jar" "/Library/Application Support/Titanium/mobilesdk/osx/3.5.0.GA/android/aps-analytics.jar" "/Library/Application Support/Titanium/mobilesdk/osx/3.5.0.GA/android/modules/titanium-android.jar" "/Library/Application Support/Titanium/mobilesdk/osx/3.5.0.GA/android/jaxen-1.1.1.jar" "/Library/Application Support/Titanium/mobilesdk/osx/3.5.0.GA/android/ti-commons-codec-1.3.jar" "/Library/Application Support/Titanium/mobilesdk/osx/3.5.0.GA/android/kroll-common.jar" "/Library/Application Support/Titanium/mobilesdk/osx/3.5.0.GA/android/titanium.jar" "/Library/Application Support/Titanium/mobilesdk/osx/3.5.0.GA/android/modules/titanium-app.jar" "/Library/Application Support/Titanium/mobilesdk/osx/3.5.0.GA/android/modules/titanium-ui.jar" "/Library/Application Support/Titanium/mobilesdk/osx/3.5.0.GA/android/nineoldandroids-appc-2.4.0.jar" "/Library/Application Support/Titanium/mobilesdk/osx/3.5.0.GA/android/modules/titanium-filesystem.jar" "/Library/Application Support/Titanium/mobilesdk/osx/3.5.0.GA/android/modules/titanium-media.jar" "/Library/Application Support/Titanium/mobilesdk/osx/3.5.0.GA/android/modules/titanium-appcompat.jar" "/Library/Application Support/Titanium/mobilesdk/osx/3.5.0.GA/android/android-support-v4.jar" "/Library/Application Support/Titanium/mobilesdk/osx/3.5.0.GA/android/android-support-v7-appcompat.jar" "/Library/Application Support/Titanium/mobilesdk/osx/3.5.0.GA/android/modules/titanium-locale.jar" "/Library/Application Support/Titanium/mobilesdk/osx/3.5.0.GA/android/modules/titanium-network.jar" "/Library/Application Support/Titanium/mobilesdk/osx/3.5.0.GA/android/thirdparty.jar" "/Library/Application Support/Titanium/mobilesdk/osx/3.5.0.GA/android/modules/titanium-xml.jar" "/Library/Application Support/Titanium/mobilesdk/osx/3.5.0.GA/android/modules/titanium-platform.jar" "/Library/Application Support/Titanium/mobilesdk/osx/3.5.0.GA/android/modules/titanium-gesture.jar" "/Library/Application Support/Titanium/mobilesdk/osx/3.5.0.GA/android/modules/titanium-geolocation.jar" "/Library/Application Support/Titanium/mobilesdk/osx/3.5.0.GA/android/modules/titanium-contacts.jar" "/Library/Application Support/Titanium/mobilesdk/osx/3.5.0.GA/android/modules/titanium-utils.jar" "/Library/Application Support/Titanium/mobilesdk/osx/3.5.0.GA/android/modules/titanium-database.jar"
[ERROR] Failed to run dexer:
[ERROR]   
[ERROR] warning: Ignoring InnerClasses attribute for an anonymous inner class
[ERROR] (org.apache.commons.logging.impl.WeakHashtable$1) that doesn't come with an
[ERROR] associated EnclosingMethod attribute. This class was probably produced by a
[ERROR] compiler that did not target the modern .class file format. The recommended
[ERROR] solution is to recompile the class from source, using an up-to-date compiler
[ERROR] and without specifying any "-target" type options. The consequence of ignoring
[ERROR] this warning is that reflective operations on this class will incorrectly
[ERROR] indicate that it is *not* an inner class.
[ERROR] warning: Ignoring InnerClasses attribute for an anonymous inner class
[ERROR] (org.apache.commons.logging.impl.LogFactoryImpl$3) that doesn't come with an
[ERROR] associated EnclosingMethod attribute. This class was probably produced by a
[ERROR] compiler that did not target the modern .class file format. The recommended
[ERROR] solution is to recompile the class from source, using an up-to-date compiler
[ERROR] and without specifying any "-target" type options. The consequence of ignoring
[ERROR] this warning is that reflective operations on this class will incorrectly
[ERROR] indicate that it is *not* an inner class.
[ERROR] warning: Ignoring InnerClasses attribute for an anonymous inner class
[ERROR] (org.apache.commons.logging.impl.LogFactoryImpl$1) that doesn't come with an
[ERROR] associated EnclosingMethod attribute. This class was probably produced by a
[ERROR] compiler that did not target the modern .class file format. The recommended
[ERROR] solution is to recompile the class from source, using an up-to-date compiler
[ERROR] and without specifying any "-target" type options. The consequence of ignoring
[ERROR] this warning is that reflective operations on this class will incorrectly
[ERROR] indicate that it is *not* an inner class.
[ERROR] warning: Ignoring InnerClasses attribute for an anonymous inner class
[ERROR] (org.apache.commons.logging.impl.SimpleLog$1) that doesn't come with an
[ERROR] associated EnclosingMethod attribute. This class was probably produced by a
[ERROR] compiler that did not target the modern .class file format. The recommended
[ERROR] solution is to recompile the class from source, using an up-to-date compiler
[ERROR] and without specifying any "-target" type options. The consequence of ignoring
[ERROR] this warning is that reflective operations on this class will incorrectly
[ERROR] indicate that it is *not* an inner class.
[ERROR] warning: Ignoring InnerClasses attribute for an anonymous inner class
[ERROR] (org.apache.commons.logging.impl.LogFactoryImpl$2) that doesn't come with an
[ERROR] associated EnclosingMethod attribute. This class was probably produced by a
[ERROR] compiler that did not target the modern .class file format. The recommended
[ERROR] solution is to recompile the class from source, using an up-to-date compiler
[ERROR] and without specifying any "-target" type options. The consequence of ignoring
[ERROR] this warning is that reflective operations on this class will incorrectly
[ERROR] indicate that it is *not* an inner class.
[ERROR] warning: Ignoring InnerClasses attribute for an anonymous inner class
[ERROR] (org.apache.commons.logging.LogFactory$4) that doesn't come with an
[ERROR] associated EnclosingMethod attribute. This class was probably produced by a
[ERROR] compiler that did not target the modern .class file format. The recommended
[ERROR] solution is to recompile the class from source, using an up-to-date compiler
[ERROR] and without specifying any "-target" type options. The consequence of ignoring
[ERROR] this warning is that reflective operations on this class will incorrectly
[ERROR] indicate that it is *not* an inner class.
[ERROR] warning: Ignoring InnerClasses attribute for an anonymous inner class
[ERROR] (org.apache.commons.logging.LogFactory$3) that doesn't come with an
[ERROR] associated EnclosingMethod attribute. This class was probably produced by a
[ERROR] compiler that did not target the modern .class file format. The recommended
[ERROR] solution is to recompile the class from source, using an up-to-date compiler
[ERROR] and without specifying any "-target" type options. The consequence of ignoring
[ERROR] this warning is that reflective operations on this class will incorrectly
[ERROR] indicate that it is *not* an inner class.
[ERROR] warning: Ignoring InnerClasses attribute for an anonymous inner class
[ERROR] (org.apache.commons.logging.LogFactory$6) that doesn't come with an
[ERROR] associated EnclosingMethod attribute. This class was probably produced by a
[ERROR] compiler that did not target the modern .class file format. The recommended
[ERROR] solution is to recompile the class from source, using an up-to-date compiler
[ERROR] and without specifying any "-target" type options. The consequence of ignoring
[ERROR] this warning is that reflective operations on this class will incorrectly
[ERROR] indicate that it is *not* an inner class.
[ERROR] warning: Ignoring InnerClasses attribute for an anonymous inner class
[ERROR] (org.apache.commons.logging.LogFactory$5) that doesn't come with an
[ERROR] associated EnclosingMethod attribute. This class was probably produced by a
[ERROR] compiler that did not target the modern .class file format. The recommended
[ERROR] solution is to recompile the class from source, using an up-to-date compiler
[ERROR] and without specifying any "-target" type options. The consequence of ignoring
[ERROR] this warning is that reflective operations on this class will incorrectly
[ERROR] indicate that it is *not* an inner class.
[ERROR] warning: Ignoring InnerClasses attribute for an anonymous inner class
[ERROR] (org.apache.commons.logging.LogFactory$1) that doesn't come with an
[ERROR] associated EnclosingMethod attribute. This class was probably produced by a
[ERROR] compiler that did not target the modern .class file format. The recommended
[ERROR] solution is to recompile the class from source, using an up-to-date compiler
[ERROR] and without specifying any "-target" type options. The consequence of ignoring
[ERROR] this warning is that reflective operations on this class will incorrectly
[ERROR] indicate that it is *not* an inner class.
[ERROR] warning: Ignoring InnerClasses attribute for an anonymous inner class
[ERROR] (org.apache.commons.logging.LogFactory$2) that doesn't come with an
[ERROR] associated EnclosingMethod attribute. This class was probably produced by a
[ERROR] compiler that did not target the modern .class file format. The recommended
[ERROR] solution is to recompile the class from source, using an up-to-date compiler
[ERROR] and without specifying any "-target" type options. The consequence of ignoring
[ERROR] this warning is that reflective operations on this class will incorrectly
[ERROR] indicate that it is *not* an inner class.
[ERROR] warning: Ignoring InnerClasses attribute for an anonymous inner class
[ERROR] (Acme.Serve.Main$1) that doesn't come with an
[ERROR] associated EnclosingMethod attribute. This class was probably produced by a
[ERROR] compiler that did not target the modern .class file format. The recommended
[ERROR] solution is to recompile the class from source, using an up-to-date compiler
[ERROR] and without specifying any "-target" type options. The consequence of ignoring
[ERROR] this warning is that reflective operations on this class will incorrectly
[ERROR] indicate that it is *not* an inner class.
[ERROR] warning: Ignoring InnerClasses attribute for an anonymous inner class
[ERROR] (Acme.Serve.Main$2) that doesn't come with an
[ERROR] associated EnclosingMethod attribute. This class was probably produced by a
[ERROR] compiler that did not target the modern .class file format. The recommended
[ERROR] solution is to recompile the class from source, using an up-to-date compiler
[ERROR] and without specifying any "-target" type options. The consequence of ignoring
[ERROR] this warning is that reflective operations on this class will incorrectly
[ERROR] indicate that it is *not* an inner class.
[ERROR] warning: Ignoring InnerClasses attribute for an anonymous inner class
[ERROR] (Acme.Serve.Main$3) that doesn't come with an
[ERROR] associated EnclosingMethod attribute. This class was probably produced by a
[ERROR] compiler that did not target the modern .class file format. The recommended
[ERROR] solution is to recompile the class from source, using an up-to-date compiler
[ERROR] and without specifying any "-target" type options. The consequence of ignoring
[ERROR] this warning is that reflective operations on this class will incorrectly
[ERROR] indicate that it is *not* an inner class.
[ERROR] warning: Ignoring InnerClasses attribute for an anonymous inner class
[ERROR] (Acme.Serve.Serve$1) that doesn't come with an
[ERROR] associated EnclosingMethod attribute. This class was probably produced by a
[ERROR] compiler that did not target the modern .class file format. The recommended
[ERROR] solution is to recompile the class from source, using an up-to-date compiler
[ERROR] and without specifying any "-target" type options. The consequence of ignoring
[ERROR] this warning is that reflective operations on this class will incorrectly
[ERROR] indicate that it is *not* an inner class.
[ERROR] warning: Ignoring InnerClasses attribute for an anonymous inner class
[ERROR] (Acme.Serve.Serve$2) that doesn't come with an
[ERROR] associated EnclosingMethod attribute. This class was probably produced by a
[ERROR] compiler that did not target the modern .class file format. The recommended
[ERROR] solution is to recompile the class from source, using an up-to-date compiler
[ERROR] and without specifying any "-target" type options. The consequence of ignoring
[ERROR] this warning is that reflective operations on this class will incorrectly
[ERROR] indicate that it is *not* an inner class.
[ERROR] warning: Ignoring InnerClasses attribute for an anonymous inner class
[ERROR] (Acme.Serve.Serve$3) that doesn't come with an
[ERROR] associated EnclosingMethod attribute. This class was probably produced by a
[ERROR] compiler that did not target the modern .class file format. The recommended
[ERROR] solution is to recompile the class from source, using an up-to-date compiler
[ERROR] and without specifying any "-target" type options. The consequence of ignoring
[ERROR] this warning is that reflective operations on this class will incorrectly
[ERROR] indicate that it is *not* an inner class.
[ERROR] warning: Ignoring InnerClasses attribute for an anonymous inner class
[ERROR] (Acme.Serve.Serve$SimpleRequestDispatcher$1) that doesn't come with an
[ERROR] associated EnclosingMethod attribute. This class was probably produced by a
[ERROR] compiler that did not target the modern .class file format. The recommended
[ERROR] solution is to recompile the class from source, using an up-to-date compiler
[ERROR] and without specifying any "-target" type options. The consequence of ignoring
[ERROR] this warning is that reflective operations on this class will incorrectly
[ERROR] indicate that it is *not* an inner class.
[ERROR] warning: Ignoring InnerClasses attribute for an anonymous inner class
[ERROR] (Acme.Serve.Serve$SimpleRequestDispatcher$2) that doesn't come with an
[ERROR] associated EnclosingMethod attribute. This class was probably produced by a
[ERROR] compiler that did not target the modern .class file format. The recommended
[ERROR] solution is to recompile the class from source, using an up-to-date compiler
[ERROR] and without specifying any "-target" type options. The consequence of ignoring
[ERROR] this warning is that reflective operations on this class will incorrectly
[ERROR] indicate that it is *not* an inner class.
[ERROR] warning: Ignoring InnerClasses attribute for an anonymous inner class
[ERROR] (Acme.Utils$1) that doesn't come with an
[ERROR] associated EnclosingMethod attribute. This class was probably produced by a
[ERROR] compiler that did not target the modern .class file format. The recommended
[ERROR] solution is to recompile the class from source, using an up-to-date compiler
[ERROR] and without specifying any "-target" type options. The consequence of ignoring
[ERROR] this warning is that reflective operations on this class will incorrectly
[ERROR] indicate that it is *not* an inner class.
[ERROR] warning: Ignoring InnerClasses attribute for an anonymous inner class
[ERROR] (Acme.Utils$DummyPrintStream$1) that doesn't come with an
[ERROR] associated EnclosingMethod attribute. This class was probably produced by a
[ERROR] compiler that did not target the modern .class file format. The recommended
[ERROR] solution is to recompile the class from source, using an up-to-date compiler
[ERROR] and without specifying any "-target" type options. The consequence of ignoring
[ERROR] this warning is that reflective operations on this class will incorrectly
[ERROR] indicate that it is *not* an inner class.
[ERROR]   
[ERROR] UNEXPECTED TOP-LEVEL ERROR:
[ERROR] java.lang.OutOfMemoryError: Java heap space
[ERROR]         at com.android.dx.cf.code.RopperMachine.run(RopperMachine.java:630)
[ERROR]         at com.android.dx.cf.code.Simulator$SimVisitor.visitBranch(Simulator.java:740)
[ERROR]         at com.android.dx.cf.code.BytecodeArray.parseInstruction(BytecodeArray.java:705)
[ERROR]         at com.android.dx.cf.code.Simulator.simulate(Simulator.java:94)
[ERROR]         at com.android.dx.cf.code.Ropper.processBlock(Ropper.java:787)
[ERROR]         at com.android.dx.cf.code.Ropper.doit(Ropper.java:742)
[ERROR]         at com.android.dx.cf.code.Ropper.convert(Ropper.java:349)
[ERROR]         at com.android.dx.dex.cf.CfTranslator.processMethods(CfTranslator.java:280)
[ERROR]         at com.android.dx.dex.cf.CfTranslator.translate0(CfTranslator.java:137)
[ERROR]         at com.android.dx.dex.cf.CfTranslator.translate(CfTranslator.java:93)
[ERROR]         at com.android.dx.command.dexer.Main.processClass(Main.java:729)
[ERROR]         at com.android.dx.command.dexer.Main.processFileBytes(Main.java:673)
[ERROR]         at com.android.dx.command.dexer.Main.access$300(Main.java:83)
[ERROR]         at com.android.dx.command.dexer.Main$1.processFileBytes(Main.java:602)
[ERROR]         at com.android.dx.cf.direct.ClassPathOpener.processArchive(ClassPathOpener.java:284)
[ERROR]         at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:166)
[ERROR]         at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:144)
[ERROR]         at com.android.dx.command.dexer.Main.processOne(Main.java:632)
[ERROR]         at com.android.dx.command.dexer.Main.processAllFiles(Main.java:510)
[ERROR]         at com.android.dx.command.dexer.Main.runMonoDex(Main.java:280)
[ERROR]         at com.android.dx.command.dexer.Main.run(Main.java:246)
[ERROR]         at com.android.dx.command.dexer.Main.main(Main.java:215)
[ERROR]         at com.android.dx.command.Main.main(Main.java:106)

**Comment by pegli** [comment]
The `warning: Ignoring InnerClasses attribute...` error is displayed because some of the JAR files in your project were compiled for Java 6 (e.g. [this StackOverflow question](http://stackoverflow.com/questions/3308010/what-is-the-ignoring-innerclasses-attribute-warning-output-during-compilation)).  I did find a possible fix [here](https://gist.github.com/grantland/3949145), but you shouldn't actually need to worry about it.  The out of memory error is probably happening because the Titanium build tool is running the dexer with 1g of memory (`-Xmx1024M`).  You can try increasing that value to 2g by setting the `_JAVA_OPTIONS` environment variable to `-Xmx2g`) as per http://forums.xamarin.com/discussion/2132/java-heap-space-outofmemoryerror-when-binding-a-big-jar.  I haven't seen the out of memory error myself, but my test applications don't use the Facebook and maps libraries like yours does.
