### ISSUE TITLE
Android: crash on large database [local reference table overflow (max=512)]

### ISSUE THREAD

**Issue by giantfrog** [pegli/ti_touchdb#93]
I will email you a Test Case to experiment with.

A fairly large 85MB (~2700 document) database with a large number of images. When displaying in a listView on Android there is a crash on a concurrent load, though sometimes it also crashes on the initial load. iOS works fine.

It seems to have something to do with the image attachments. Works fine on a ~3500+ document database without images as well as smaller databases with images. On this 85MB db with images the crash will happen whether or not the image attachments are fetched and loaded.

To reproduce using the emailed Test Case:
Android- The large database will pull replicate and display the list view when replication is finished. Tap the refresh button and a few moments later the crash will happen.

iOS- Same as above but without the crash. Hit 'refresh' as often as you like. See the comments at the top of ui/common/FirstView.js

Ti Studio 3.4.1, SDK 3.4.1, Touchdb 1.2.0

```
[DEBUG] :  dalvikvm: GC_FOR_ALLOC freed 2036K, 8% free 88282K/95856K, paused 30ms, total 30ms
[DEBUG] :  dalvikvm: GC_FOR_ALLOC freed 1920K, 8% free 89096K/96356K, paused 28ms, total 28ms
[INFO] :   I/dalvikvm-heap: Clamp target GC heap from 96.129MB to 96.000MB
[DEBUG] :  dalvikvm: GC_FOR_ALLOC freed 2159K, 8% free 90135K/97356K, paused 32ms, total 32ms
[ERROR] :  dalvikvm: JNI ERROR (app bug): local reference table overflow (max=512)
[WARN] :   dalvikvm: JNI local reference table (0xb8f15770) dump:
[WARN] :   dalvikvm:   Last 10 entries (of 512):
[WARN] :   dalvikvm:       511: 0xa4d43a38 android.graphics.Bitmap$Config
[WARN] :   dalvikvm:       510: 0xa6081b30 android.graphics.BitmapFactory$Options
[WARN] :   dalvikvm:       509: 0xaac7ec60 byte[] (271641 elements)
[WARN] :   dalvikvm:       508: 0xa4d763d0 java.lang.Class<android.graphics.BitmapFactory>
[WARN] :   dalvikvm:       507: 0xa695b408 com.obscure.titouchdb.AttachmentProxy
[WARN] :   dalvikvm:       506: 0xa59d9288 com.obscure.titouchdb.DocumentProxy
[WARN] :   dalvikvm:       505: 0xa599dc08 com.obscure.titouchdb.SavedRevisionProxy
[WARN] :   dalvikvm:       504: 0xa5a94b08 com.obscure.titouchdb.DocumentProxy
[WARN] :   dalvikvm:       503: 0xa5a3f560 com.obscure.titouchdb.SavedRevisionProxy
[WARN] :   dalvikvm:       502: 0xa5b86128 com.obscure.titouchdb.DocumentProxy
[WARN] :   dalvikvm:   Summary:
[WARN] :   dalvikvm:         1 of java.lang.Class
[WARN] :   dalvikvm:         1 of java.lang.String
[WARN] :   dalvikvm:         1 of byte[] (271641 elements)
[WARN] :   dalvikvm:         1 of android.graphics.Bitmap$Config
[WARN] :   dalvikvm:         1 of android.graphics.BitmapFactory$Options
[WARN] :   dalvikvm:         1 of org.appcelerator.kroll.runtime.v8.V8Object
[WARN] :   dalvikvm:         1 of org.appcelerator.kroll.KrollDict
[WARN] :   dalvikvm:       252 of com.obscure.titouchdb.SavedRevisionProxy (252 unique instances)
[WARN] :   dalvikvm:         1 of com.obscure.titouchdb.AttachmentProxy
[WARN] :   dalvikvm:       252 of com.obscure.titouchdb.DocumentProxy (252 unique instances)
[ERROR] :  dalvikvm: Failed adding to JNI local ref table (has 512 entries)
[INFO] :   dalvikvm: "KrollRuntimeThread" prio=5 tid=11 RUNNABLE
[INFO] :   dalvikvm:   | group="main" sCount=0 dsCount=0 obj=0xa5108f00 self=0xb8c8a270
[INFO] :   dalvikvm:   | sysTid=10122 nice=0 sched=0/0 cgrp=apps handle=-1194740064
[INFO] :   dalvikvm:   | state=R schedstat=( 13674430878 6502704503 6387 ) utm=772 stm=594 core=2
[INFO] :   dalvikvm:   at android.graphics.BitmapFactory.nativeDecodeByteArray(Native Method)
[INFO] :   dalvikvm:   at android.graphics.BitmapFactory.decodeByteArray(BitmapFactory.java:507)
[INFO] :   dalvikvm:   at org.appcelerator.titanium.TiBlob.loadBitmapInfo(TiBlob.java:239)
[INFO] :   dalvikvm:   at org.appcelerator.titanium.TiBlob.blobFromData(TiBlob.java:194)
[INFO] :   dalvikvm:   at com.obscure.titouchdb.AttachmentProxy.getContent(AttachmentProxy.java:54)
[INFO] :   dalvikvm:   at com.obscure.titouchdb.AttachmentProxy.getContentURL(AttachmentProxy.java:74)
[INFO] :   dalvikvm:   at org.appcelerator.kroll.runtime.v8.V8Object.nativeFireEvent(Native Method)
[INFO] :   dalvikvm:   at org.appcelerator.kroll.runtime.v8.V8Object.fireEvent(V8Object.java:62)
[INFO] :   dalvikvm:   at org.appcelerator.kroll.KrollProxy.doFireEvent(KrollProxy.java:884)
[INFO] :   dalvikvm:   at org.appcelerator.kroll.KrollProxy.handleMessage(KrollProxy.java:1107)
[INFO] :   dalvikvm:   at org.appcelerator.titanium.proxy.TiViewProxy.handleMessage(TiViewProxy.java:347)
[INFO] :   dalvikvm:   at android.os.Handler.dispatchMessage(Handler.java:98)
[INFO] :   dalvikvm:   at android.os.Looper.loop(Looper.java:136)
[INFO] :   dalvikvm:   at org.appcelerator.kroll.KrollRuntime$KrollRuntimeThread.run(KrollRuntime.java:112)
[INFO] :   dalvikvm:
[ERROR] :  dalvikvm: VM aborting
[INFO] :   libc: Fatal signal 6 (SIGABRT) at 0x00002778 (code=-6), thread 10122 (KrollRuntimeThr)
```

**Comment by pegli** [comment]
Hi Doug -

It looks like you've discovered a memory leak in TiTouchDB-Android.  Document objects cache a copy of the current revision object.  When I remove that cached copy and run your test app in the Genymotion emulator, I am able to press the reload button a couple of times without any trouble.  After a few reloads, however, I see an out of memory exception in the attachment binary data handing code.  I'm working on that problem now and should be able to send you a build of the module for testing some time tomorrow.

p.

**Comment by giantfrog** [comment]
Sweet!


http://www.PrepAndPantry.com
