### ISSUE TITLE
Android: Save image attachment then immediate getAttachment crashes app

### ISSUE THREAD

**Issue by giantfrog** [pegli/ti_touchdb#94]
Take a picture. Save as an attachment. Retrieve the attachment. Crash.
```
Message: Uncaught Error: md5-ahFL14UngCMkot+sDAEjBA== did not start with sha1-
```

The oddity is that in my production app I can ignore the crash, save the document I am working on, go back to my list view, refresh the list view and the image is there.

I will email a test case to reproduce.

Studio 3.4.1, sdk 3.5.0.GA, Titouchdb 1.2.1 - Android

```
[WARN] :   W/System.err: java.lang.IllegalArgumentException: md5-byKvDZl5w2vi21esmQt5Bw== did not start with sha1-
[WARN] :   W/System.err: 	at com.couchbase.lite.BlobKey.decodeBase64Digest(BlobKey.java:62)
[WARN] :   W/System.err: 	at com.couchbase.lite.BlobKey.<init>(BlobKey.java:48)
[WARN] :   W/System.err: 	at com.obscure.titouchdb.AttachmentProxy.<init>(AttachmentProxy.java:50)
[WARN] :   W/System.err: 	at com.obscure.titouchdb.AbstractRevisionProxy.getAttachment(AbstractRevisionProxy.java:47)
[WARN] :   W/System.err: 	at org.appcelerator.kroll.runtime.v8.V8Function.nativeInvoke(Native Method)
[WARN] :   W/System.err: 	at org.appcelerator.kroll.runtime.v8.V8Function.callSync(V8Function.java:57)
[WARN] :   W/System.err: 	at org.appcelerator.kroll.runtime.v8.V8Function.call(V8Function.java:43)
[WARN] :   W/System.err: 	at org.appcelerator.kroll.runtime.v8.V8Function$1.run(V8Function.java:70)
[WARN] :   W/System.err: 	at android.os.Handler.handleCallback(Handler.java:733)
[WARN] :   W/System.err: 	at android.os.Handler.dispatchMessage(Handler.java:95)
[WARN] :   W/System.err: 	at android.os.Looper.loop(Looper.java:136)
[WARN] :   W/System.err: 	at org.appcelerator.kroll.KrollRuntime$KrollRuntimeThread.run(KrollRuntime.java:112)
[ERROR] :  TiExceptionHandler: (main) [10104,10104] ----- Titanium Javascript Runtime Error -----
[ERROR] :  TiExceptionHandler: (main) [0,10104] - In ui/common/FirstView.js:33,27
[ERROR] :  TiExceptionHandler: (main) [0,10104] - Message: Uncaught Error: md5-byKvDZl5w2vi21esmQt5Bw== did not start with sha1-
[ERROR] :  TiExceptionHandler: (main) [0,10104] - Source:             var att = rev.getAttachment(itemBarcode + '_image.png');
[DEBUG] :  dalvikvm: GC_CONCURRENT freed 978K, 8% free 11808K/12820K, paused 5ms+1ms, total 23ms
[WARN] :   CursorWrapperInner: Cursor finalized without prior close()
[ERROR] :  V8Exception: Exception occurred at ui/common/FirstView.js:33: Uncaught Error: md5-byKvDZl5w2vi21esmQt5Bw== did not start with sha1-
```

**Comment by pegli** [comment]
Part of the fix for memory usage in AttachmentProxy was to use the attachment files to construct blob objects for use in Titanium.  Couchbase Lite uses the attachment body's SHA1 digest as a key to locate the file on disk.  I was getting the digest from the attachment's metadata, which always appeared to be a SHA1, but this stack trace shows an MD5 digest.  I've modified the code to look for a SHA1 digest specifically, and if it isn't found, to generate one in a memory-efficent manner using the MessageDigest class.  The test case you sent runs fine with the updated code.
